name: Deploy to Firebase Hosting on PR Merge

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest  # Use Ubuntu for GitHub Actions runner

    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # Check out the code from GitHub repository

      - name: Set up Flutter
        uses: subosito/flutter-action@v2  # Set up Flutter environment
        with:
          flutter-version: 'stable'  # Install the stable version of Flutter

      - name: Install dependencies
        run: |
          flutter pub get  # Get Flutter dependencies
          npm ci            # Install npm dependencies

      - name: Build Flutter web
        run: flutter build web  # Build the Flutter web app

      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0  # Deploy to Firebase Hosting
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}  # GitHub Token for authentication
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_BITE_BOX_DBEBE }}  # Firebase service account key
          channelId: live  # Deploy to the live channel
          projectId: bite-box-dbebe  # Your Firebase project ID
