name: Firebase Hosting Pull Request

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest  # Use Ubuntu for GitHub Actions runner

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: 'stable'  # Install the stable version of Flutter

    - name: Install dependencies
      run: |
        flutter pub get  # Get Flutter dependencies
        npm ci            # Install npm dependencies

    - name: Build Flutter web
      run: flutter build web  # Build the web app for Firebase Hosting

    - name: Deploy to Firebase Hosting
      run: firebase deploy --only hosting --token ${{ secrets.FIREBASE_TOKEN }}  # Deploy to Firebase Hosting
