name: Firebase Hosting Pull Request

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: 'stable'  # You can specify other versions if needed

    - name: Install dependencies
      run: |
        flutter pub get  # Get Flutter dependencies
        npm ci            # Install npm dependencies

    - name: Build Flutter web
      run: flutter build web  # Build the web app

    - name: Deploy to Firebase Hosting
      run: firebase deploy --only hosting --token ${{ secrets.FIREBASE_TOKEN }}
